export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ALL_COURSES_START = "GET_ALL_COURSES_START";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAIL = "GET_ALL_COURSES_FAIL";

export const GET_ENROLLED_COURSES_START = "GET_ENROLLED_COURSES_START";
export const GET_ENROLLED_COURSES_SUCCESS = "GET_ENROLLED_COURSES_SUCCESS";
export const GET_ENROLLED_COURSES_FAIL = "GET_ENROLLED_COURSES_FAIL";

export const STUDENT_UPDATE_START = "STUDENT_UPDATE_START";
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAIL = "STUDENT_UPDATE_FAIL";

export const FETCH_ENROLLED_COURSE_START = "FETCH_ENROLLED_COURSE_START";
export const FETCH_ENROLLED_COURSE_SUCCESS = "FETCH_ENROLLED_COURSE_SUCCESS";

export const GET_ALL_INVOICES_START = "GET_ALL_INVOICES_START";
export const GET_ALL_INVOICES_SUCCESS = "GET_ALL_INVOICES_SUCCESS";

export const GET_FINANCE_ACCOUNT_INFO_START = "GET_FINANCE_ACCOUNT_INFO_START";
export const GET_FINANCE_ACCOUNT_INFO_SUCCESS =
  "GET_FINANCE_ACCOUNT_INFO_SUCCESS";

export const GET_ALL_SEARCH_COURSES_START = "GET_ALL_SEARCH_COURSES_START";
export const GET_ALL_SEARCH_COURSES_SUCCESS = "GET_ALL_SEARCH_COURSES_SUCCESS";
export const GET_ALL_SEARCH_COURSES_FINISH = "GET_ALL_SEARCH_COURSES_FINISH";
